FROM node:11.9.0-alpine

# autor da imagem
MAINTAINER Rodrigo M. Mariano <rodrigo.mariano at inpe.br>

# faz da pasta 'app' o diretório atual de trabalho
WORKDIR /app

# expõem a porta 8080
EXPOSE 8080

# o comando que será executado pelo container, quando este for criado por esta imagem
CMD [ "npm", "run", "serve" ]